version: '3'

vars:
  APP_NAME:
    sh: echo "${APP_NAME:-$(basename $(pwd))}"
  APP_VERSION:
    sh: echo "${APP_VERSION:-$(git rev-parse --abbrev-ref HEAD)}"
  ARCH:
    sh: echo "${ARCH:-$(uname -m)}"

includes:
  go:
    taskfile: .ci/go/Taskfile.yaml
    optional: true

tasks:
  init:
    desc: Initialize environment
    cmds:
      - rm -rf .ci
      - git clone --branch v1 https://github.com/ashep/ci.git .ci
