version: '3'

includes:
  go:
    taskfile: .ci/go/Taskfile.yaml
    optional: true

tasks:
  init:
    desc: Initialize environment
    cmds:
      - rm -rf .ci
      - git clone --branch v1 https://github.com/ashep/ci.git .ci
